commented plan status

diff --git a/.github/workflows/terraform-for-aws.yml b/.github/workflows/terraform-for-aws.yml
--- a/.github/workflows/terraform-for-aws.yml
+++ b/.github/workflows/terraform-for-aws.yml
@@ -42,9 +42,9 @@ jobs:
         run: terraform plan
         continue-on-error: true
         
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
         
       - name: Terraform Apply
         id: apply
